fix: release

diff --git a/.github/workflows/goreleaser.yaml b/.github/workflows/goreleaser.yaml
--- a/.github/workflows/goreleaser.yaml
+++ b/.github/workflows/goreleaser.yaml
@@ -6,8 +6,69 @@ on:
       - v*
 
 jobs:
+  validate:
+    runs-on: ubuntu-latest
+    name: Validate Release
+    outputs:
+      COMMIT_SHA: ${{ steps.commit-sha.outputs.commit_sha }}
+      FLAGS: ${{ steps.set-flags.outputs.flags }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v5
+
+      - name: Setup Node
+        uses: actions/setup-node@v5
+        with:
+          node-version: '20'
+
+      - name: Commit SHA
+        id: commit-sha
+        run: echo "commit_sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
+
+      - name: Validate Release
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        # This step validates that the tag is an official release
+        id: set-flags
+        run: |
+          prerelease=$(gh release view ${{ github.ref_name }} --json isPrerelease | jq -r '.isPrerelease')
+          
+          version="${{ github.ref_name }}"
+          
+          if [ "$prerelease" == "true" ]; then
+          
+            echo "flags=--nightly" >> $GITHUB_ENV
+            echo "flags=--nightly" >> "$GITHUB_OUTPUT"
+          
+            # if it does not contain 'rc', it's invalid
+            if [[ "${{ github.ref_name }}" != *-rc* ]]; then
+                echo "Tag is a prerelease, but the tag name does not contain -rc"
+                exit 1
+            fi
+          
+            version="${version#v}"  # Remove the "v" prefix from the tag
+            version="${version%%-rc.*}" # Remove the "-rc.*" suffix from the tag
+          else
+            echo "flags=" >> $GITHUB_ENV
+            echo "flags=" >> "$GITHUB_OUTPUT"
+            node -e "if (!/^v\d+\.\d+\.\d+$/.test('${{ github.ref_name }}')) { console.error('Invalid version format. Expected: vX.Y.Z'); process.exit(1); }"
+            version="${version#v}"  # Remove the "v" prefix from the tag
+          fi
+          
+          thor_version=$(cat cmd/thor/VERSION)
+          if [ "$version" != "$thor_version" ]; then
+            echo "VERSION file ($thor_version) does not match tag ($version)"
+          exit 1
+          
+          api_version=$(grep -o 'version: [0-9.]*' api/doc/thor.yaml | awk '{print $2}')
+          if [ "$version" != "$api_version" ]; then
+              echo "API spec version ($api_version) does not match Thor version ($version)"
+              exit 1
+          fi
+          
   prepare:
     runs-on: ${{ matrix.runs-on }}
+    needs: validate
     strategy:
       fail-fast: false
       matrix:
@@ -39,11 +100,6 @@ jobs:
         with:
           go-version: 1.24
 
-      - if: contains(github.ref, 'rc')
-        shell: bash
-        run: |
-          echo "flags=--nightly" >> $GITHUB_ENV
-
       - uses: docker/setup-qemu-action@v3
         if: matrix.go-os == 'linux'
       - uses: docker/setup-buildx-action@v3
@@ -64,7 +120,7 @@ jobs:
       - uses: actions/cache@v4
         with:
           path: dist/${{ matrix.go-os }}_${{ matrix.go-arch }}
-          key: ${{ matrix.go-os }}-${{ env.sha_short }}${{ env.flags }}-${{ matrix.go-arch }}
+          key: ${{ matrix.go-os }}-${{ needs.validate.outputs.COMMIT_SHA }}${{ needs.validate.outputs.FLAGS }}-${{ matrix.go-arch }}
 
       - name: Set Up Env
         id: env
@@ -81,7 +137,7 @@ jobs:
         with:
           distribution: goreleaser-pro
           version: latest
-          args: release --clean --split --verbose ${{ env.flags }} ${{ (matrix.go-os == 'darwin' || matrix.go-os == 'windows') && '--skip docker' || ''}}
+          args: release --clean --split --verbose ${{ needs.validate.outputs.FLAGS }} ${{ (matrix.go-os == 'darwin' || matrix.go-os == 'windows') && '--skip docker' || ''}}
         env:
           GITHUB_TOKEN: ${{ github.token }}
           GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
@@ -98,7 +154,9 @@ jobs:
 
   release:
     runs-on: ubuntu-latest
-    needs: prepare
+    needs:
+      - prepare
+      - validate
     env:
       DOCKER_CLI_EXPERIMENTAL: "enabled"
       flags: ""
@@ -132,24 +190,24 @@ jobs:
           echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
       - uses: actions/cache@v4
         with:
-          path: dist/linux-amd64
-          key: linux_${{ env.sha_short }}${{ env.flags }}-amd64
+          path: dist/linux_amd64
+          key: linux-${{ needs.validate.outputs.COMMIT_SHA }}${{ needs.validate.outputs.FLAGS }}-amd64
       - uses: actions/cache@v4
         with:
-          path: dist/linux-arm64
-          key: linux_${{ env.sha_short }}${{ env.flags }}-arm64
+          path: dist/linux_arm64
+          key: linux-${{ needs.validate.outputs.COMMIT_SHA }}${{ needs.validate.outputs.FLAGS }}-arm64
       - uses: actions/cache@v4
         with:
-          path: dist/darwin
-          key: darwin_${{ env.sha_short }}${{ env.flags }}-arm64
+          path: dist/darwin_arm64
+          key: darwin-${{ needs.validate.outputs.COMMIT_SHA }}${{ needs.validate.outputs.FLAGS }}-arm64
       - uses: actions/cache@v4
         with:
-          path: dist/windows
-          key: windows_${{ env.sha_short }}${{ env.flags }}-amd64
+          path: dist/windows_amd64
+          key: windows-${{ needs.validate.outputs.COMMIT_SHA }}${{ needs.validate.outputs.FLAGS }}-amd64
           enableCrossOsArchive: true
       - name: Debug
         run: ls -laR ./dist
-        
+
       - uses: goreleaser/goreleaser-action@v6
         with:
           distribution: goreleaser-pro
